package com.model.pojo;
// Generated Sep 20, 2024 2:26:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private String username;
     private String email;
     private String password;
     private String statusAdmin;
     private Set otpcodes = new HashSet(0);

    public Admin() {
    }

	
    public Admin(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }
    public Admin(String username, String email, String password, String statusAdmin, Set otpcodes) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.statusAdmin = statusAdmin;
       this.otpcodes = otpcodes;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatusAdmin() {
        return this.statusAdmin;
    }
    
    public void setStatusAdmin(String statusAdmin) {
        this.statusAdmin = statusAdmin;
    }
    public Set getOtpcodes() {
        return this.otpcodes;
    }
    
    public void setOtpcodes(Set otpcodes) {
        this.otpcodes = otpcodes;
    }




}


