package com.model.pojo;
// Generated Sep 20, 2024 2:26:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private int brandId;
     private String brandName;
     private Set items = new HashSet(0);

    public Brand() {
    }

	
    public Brand(int brandId, String brandName) {
        this.brandId = brandId;
        this.brandName = brandName;
    }
    public Brand(int brandId, String brandName, Set items) {
       this.brandId = brandId;
       this.brandName = brandName;
       this.items = items;
    }
   
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


