package com.model.pojo;
// Generated Sep 20, 2024 2:26:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Base64;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int itemId;
     private Brand brand;
     private String itemName;
     private BigDecimal price;
     private String description;

     private byte[] image;
     private int stocks;


     private Set orderItemses = new HashSet(0);
     private String imageBase64;
  private int quantity;

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public Item() {
    }

	
    public Item(int itemId, Brand brand, String itemName, BigDecimal price, int stocks, int quantity) {
        this.itemId = itemId;
        this.brand = brand;
        this.itemName = itemName;
        this.price = price;
        this.stocks = stocks;
        this.quantity=quantity;
    }
    public Item(int itemId, Brand brand, String itemName, BigDecimal price, String description, byte[] image, int stocks, String sizes, Set orderItemses, int quantity) {
       this.itemId = itemId;
       this.brand = brand;
       this.itemName = itemName;
       this.price = price;
       this.description = description;
       this.image = image;
       this.stocks = stocks;
       this.orderItemses = orderItemses;
       this.quantity=quantity;
    }
   
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public int getStocks() {
        return this.stocks;
    }
    
    public void setStocks(int stocks) {
        this.stocks = stocks;
    }

    public Set getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set orderItemses) {
        this.orderItemses = orderItemses;
    }


public String getImageBase64() {
    return imageBase64;
}

public void setImageBase64(String imageBase64) {
    this.imageBase64 = imageBase64;
}

@Override
public boolean equals(Object obj) {
    if (this == obj) return true;
    if (!(obj instanceof Item)) return false;
    Item item = (Item) obj;
    return itemId == item.itemId; // atau atribut unik lainnya
}

@Override
public int hashCode() {
    return Objects.hash(itemId);
}

    // New method to return image URL (base64 encoded image)
    public String getImageUrl() {
        // If the image is available as Base64, return the proper URL format
        if (image != null && image.length > 0) {
            return "data:image/png;base64," + Base64.getEncoder().encodeToString(image);
        }
        // Otherwise, return null or a default placeholder
        return "/images/default.png";  // Return a default image if no image is available
    }


}


