package com.model.pojo;
// Generated Sep 20, 2024 2:26:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Otpcode generated by hbm2java
 */
public class Otpcode  implements java.io.Serializable {


     private Integer otpId;
     private Admin admin;
     private User user;
     private String authCode;
     private Date expiryTime;
     private Boolean isUsed;

    public Otpcode() {
    }

	
    public Otpcode(String authCode, Date expiryTime) {
        this.authCode = authCode;
        this.expiryTime = expiryTime;
    }
    public Otpcode(Admin admin, User user, String authCode, Date expiryTime, Boolean isUsed) {
       this.admin = admin;
       this.user = user;
       this.authCode = authCode;
       this.expiryTime = expiryTime;
       this.isUsed = isUsed;
    }
   
    public Integer getOtpId() {
        return this.otpId;
    }
    
    public void setOtpId(Integer otpId) {
        this.otpId = otpId;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAuthCode() {
        return this.authCode;
    }
    
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }
    public Date getExpiryTime() {
        return this.expiryTime;
    }
    
    public void setExpiryTime(Date expiryTime) {
        this.expiryTime = expiryTime;
    }
    public Boolean getIsUsed() {
        return this.isUsed;
    }
    
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }




}


